# Generated by Django 3.1.5 on 2021-01-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210112_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employer_name', models.CharField(max_length=45, verbose_name='Работодатель')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Работодатели',
                'verbose_name_plural': 'Работодатель',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
                ('content', models.TextField(verbose_name='Содержимое сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=40, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание должности')),
                ('salary', models.CharField(max_length=60, verbose_name='Заработная плата')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employers')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desired_position', models.CharField(max_length=40, verbose_name='Желаемая должность')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='NumberEmployees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employer_number', models.CharField(max_length=40, verbose_name='Количество работников')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employers')),
            ],
            options={
                'verbose_name': 'Количество работников',
                'verbose_name_plural': 'Количество работников',
            },
        ),
        migrations.CreateModel(
            name='EmployerRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employer_rating', models.IntegerField()),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employers')),
            ],
            options={
                'verbose_name': 'Рейтинг работодателя',
                'verbose_name_plural': 'Рейтинг работодателей',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skills', models.TextField(verbose_name='Навыки работника')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
            ],
            options={
                'verbose_name': 'Навыки работника',
                'verbose_name_plural': 'Навыки работников',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desired_salary', models.CharField(max_length=60, verbose_name='Желаемая ЗП')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
            ],
            options={
                'verbose_name': 'Желаемая ЗП работников',
                'verbose_name_plural': 'Желаемая ЗП работника',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_rating', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
            ],
            options={
                'verbose_name': 'Рейтинг работников',
                'verbose_name_plural': 'Рейтинг работника',
            },
        ),
    ]
