# Generated by Django 3.1.5 on 2021-01-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employeerating_employeesalary_employeeskills_employerrating_employers_message_numberemployees_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='resume',
            name='desired_salary',
            field=models.CharField(default='', max_length=60, verbose_name='Желаемая ЗП'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(default='', verbose_name='Навыки'),
        ),
    ]
