# Generated by Django 3.1.5 on 2021-01-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210112_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employees'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employers'),
        ),
    ]
