# Generated by Django 3.1.5 on 2021-01-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210112_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('r', 'Read'), ('n', 'Not Read')], default='n', max_length=1),
        ),
    ]
