# Generated by Django 3.1.5 on 2021-01-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('r', 'Прочитано'), ('n', 'Не прочитано')], default='n', max_length=1, verbose_name='Статус сообщения'),
        ),
    ]
